title: Defender for Identity
description: This lab showcases the deployment and the threat detection and investigation capabilities of Microsoft Defender for Identity. 
theme: just-the-docs

aux_links:
  "TechExcel Defender for Identity": 
    - "https://github.com/microsoft/TechExcel-Defender-for-Identity/"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red
